id: laser_quest
name: Laser_Quest
version: 1.0.0
author: zyzx
icon: ''
desc: Tracking laser
files:
  - blob_detect.py
  - main.py
  - menu.py
  - pid.py
  - serial_protocol.py
  - servo.py
  - threshold.py
